### ISSUE TITLE
Agregar Typescript gulp flow

### ISSUE THREAD

**Issue by molekilla** [ng-panama/ts-httpbin#1]
@edgarSucre

**Comment by edgarSucre** [comment]
vamos a compilar toda la libreria a un single service?

**Comment by edgarSucre** [comment]
@molekilla asigname el issue

**Comment by molekilla** [comment]
recuerda debe ts to js para poder subirlo a npm

**Comment by molekilla** [comment]
listo
https://github.com/ng-panama/ts-httpbin/commit/7dcc09f32a38e1db2aff5879918ddeca76251590
