### ISSUE TITLE
Agregar angular para usar $http service

### ISSUE THREAD

**Issue by molekilla** [ng-panama/ts-httpbin#2]
@bradleySuira

**Comment by bradleySuira** [comment]
@molekilla Me pongo en ello este fin de semana

**Comment by molekilla** [comment]
Por favor , crear un story para agregar el browser spec

se agrego $http a HttpBinService
https://github.com/ng-panama/ts-httpbin/commit/7dcc09f32a38e1db2aff5879918ddeca76251590
